# Generated by Django 3.2.6 on 2021-11-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0002_auto_20211106_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativecomment',
            name='comment',
            field=models.TextField(verbose_name='Commentaire Cooperative'),
        ),
        migrations.AlterField(
            model_name='membercomment',
            name='comment',
            field=models.TextField(verbose_name='Commentaire Membre'),
        ),
    ]
