# Generated by Django 3.2.6 on 2021-12-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie', '0003_auto_20211130_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie_images')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
    ]
